# Step 1: Use an official and lightweight Python runtime as a parent image
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 80

CMD ["gunicorn", "--workers", "4", "--bind", "0.0.0.0:80", "app:app"]